### ISSUE TITLE
Possibility to fetch time in hours

### ISSUE THREAD

**Issue by Vmagdesyan** [ymolchanov/curious-goran#1]
Hello @ymolchanov . 
I really enjoy using your library, but for some statuses, I want to take time in different statuses in hours.
Please, add this feature ASAP, because it's very hard to analyze the time for statuses in days.
Thank you in advance!

**Comment by ymolchanov** [comment]
Dear @Vmagdesyan I've added necessary changes to my tool. Hope these changes will help you in your day-by-day work. 👍 
Please check the version 1.1.0 of the tool.
You can check it [here](https://github.com/ymolchanov/curious-goran/commit/22cbdea7ae962fd8dffb015b53fea5cd0c687b60)
Best regards
